GEMINI_MODEL_NAME = 'gemini-2.0-flash'

INDEX_NAME = "lumos"
INDEX_NAMESPACE = "lumos"

OPENAI_LLM_MODEL = "gpt-4o"  # "o3-mini" # "gpt-4o"
OPENAI_LLM_TEMPERATURE = 0.5
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"
OPENAI_EMBEDDING_DIMENSION = 1536