GEMINI_MODEL_NAME = 'gemini-2.0-flash-lite'

INDEX_NAME = "lumos"
INDEX_NAMESPACE = "lumos"

OPENAI_LLM_MODEL = "gpt-4o"
OPENAI_LLM_TEMPERATURE = 0.0
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"
OPENAI_EMBEDDING_DIMENSION = 1536